FROM node:20

ENV RESET_HOUR=$RESET_HOUR \
    RESET_MINUTE=$RESET_MINUTE \
    NGROK_PORT=$NGROK_PORT \
    NGROK_AUTH=$NGROK_AUTH \
    NGROK_AUTH_TOKEN=$NGROK_AUTH_TOKEN \
    NGROK_REGION=$NGROK_REGION \
    WEBHOOK_URL=$WEBHOOK_URL

WORKDIR /app

COPY package.json .

RUN npm install -g yarn

RUN yarn

COPY . .

CMD ["yarn", "start"]
